CREATE TABLE TASK (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50),
    creation_date DATE,
    project_id BIGINT,
    FOREIGN KEY (project_id) REFERENCES PROJECT(id)
);