INSERT INTO TASK (TITLE, DESCRIPTION, STATUS, CREATION_DATE, PROJECT_ID) VALUES ('Tarefa 1', 'Descrição 1', 'OPEN', '2025-08-01', 1);
INSERT INTO TASK (TITLE, DESCRIPTION, STATUS, CREATION_DATE, PROJECT_ID) VALUES ('Tarefa 2', 'Descrição 2', 'OPEN', '2025-08-02', 1);
INSERT INTO TASK (TITLE, DESCRIPTION, STATUS, CREATION_DATE, PROJECT_ID) VALUES ('Tarefa 3', 'Descrição 3', 'COMPLETED', '2025-08-03', 1);
INSERT INTO TASK (TITLE, DESCRIPTION, STATUS, CREATION_DATE, PROJECT_ID) VALUES ('Tarefa 4', 'Descrição 4', 'OPEN', '2025-08-04', 1);
INSERT INTO TASK (TITLE, DESCRIPTION, STATUS, CREATION_DATE, PROJECT_ID) VALUES ('Tarefa 5', 'Descrição 5', 'OPEN', '2025-08-05', 1);

INSERT INTO TASK (TITLE, DESCRIPTION, STATUS, CREATION_DATE, PROJECT_ID) VALUES ('Tarefa 6', 'Descrição 6', 'COMPLETED', '2025-08-06', 2);
INSERT INTO TASK (TITLE, DESCRIPTION, STATUS, CREATION_DATE, PROJECT_ID) VALUES ('Tarefa 7', 'Descrição 7', 'OPEN', '2025-08-07', 2);
INSERT INTO TASK (TITLE, DESCRIPTION, STATUS, CREATION_DATE, PROJECT_ID) VALUES ('Tarefa 8', 'Descrição 8', 'OPEN', '2025-08-08', 2);
INSERT INTO TASK (TITLE, DESCRIPTION, STATUS, CREATION_DATE, PROJECT_ID) VALUES ('Tarefa 9', 'Descrição 9', 'COMPLETED', '2025-08-09', 2);
INSERT INTO TASK (TITLE, DESCRIPTION, STATUS, CREATION_DATE, PROJECT_ID) VALUES ('Tarefa 10', 'Descrição 10', 'OPEN', '2025-08-10', 2);

INSERT INTO TASK (TITLE, DESCRIPTION, STATUS, CREATION_DATE, PROJECT_ID) VALUES ('Tarefa 11', 'Descrição 11', 'OPEN', '2025-08-11', 1);
INSERT INTO TASK (TITLE, DESCRIPTION, STATUS, CREATION_DATE, PROJECT_ID) VALUES ('Tarefa 12', 'Descrição 12', 'COMPLETED', '2025-08-12', 1);
INSERT INTO TASK (TITLE, DESCRIPTION, STATUS, CREATION_DATE, PROJECT_ID) VALUES ('Tarefa 13', 'Descrição 13', 'OPEN', '2025-08-13', 2);
INSERT INTO TASK (TITLE, DESCRIPTION, STATUS, CREATION_DATE, PROJECT_ID) VALUES ('Tarefa 14', 'Descrição 14', 'COMPLETED', '2025-08-14', 2);
INSERT INTO TASK (TITLE, DESCRIPTION, STATUS, CREATION_DATE, PROJECT_ID) VALUES ('Tarefa 15', 'Descrição 15', 'OPEN', '2025-08-15', 1);